# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='send_time',
            field=models.DateTimeField(),
        ),
    ]
