# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20161122_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(max_length=300)),
                ('dianzan', models.IntegerField(default=0)),
                ('biandi', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='msg',
            name='post_time',
        ),
        migrations.AlterField(
            model_name='msg',
            name='send_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
