# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(default=False, max_length=50)),
                ('avatar_url', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_count', models.IntegerField(default=1)),
                ('fake_id', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('send_time', models.TimeField()),
                ('post_time', models.TimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.Guest')),
            ],
        ),
    ]
