# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(max_length=300)),
                ('send_time', models.DateTimeField(auto_now=True)),
                ('dianzan', models.IntegerField(default=0)),
                ('biandi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('img', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('authid', models.CharField(max_length=4)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('addr', models.CharField(default='火星', max_length=100)),
                ('forbid', models.IntegerField(default=0)),
                ('islogin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(max_length=300)),
                ('send_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
