# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_auto_20161123_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='avatar_url',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
